name: flutter_device_preview
description: A example of how to use the device_preview package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  fonts:
    - family: Rubik-Black
      fonts:
        - asset: fonts/Rubik-Black.ttf

    - family: Rubik-BlackItalic
      fonts:
        - asset: fonts/Rubik-BlackItalic.ttf

    - family: Rubik-Bold
      fonts:
        - asset: fonts/Rubik-Bold.ttf

    - family: Rubik-Bold
      fonts:
        - asset: fonts/Rubik-Bold.ttf

    - family: Rubik-BoldItalic
      fonts:
        - asset: fonts/Rubik-BoldItalic.ttf

    - family: Rubik-Italic
      fonts:
        - asset: fonts/Rubik-Italic.ttf

    - family: Rubik-Light
      fonts:
        - asset: fonts/Rubik-Light.ttf

    - family: Rubik-LightItalic
      fonts:
        - asset: fonts/Rubik-LightItalic.ttf

    - family: Rubik-Medium
      fonts:
        - asset: fonts/Rubik-Medium.ttf

    - family: Rubik-MediumItalic
      fonts:
        - asset: fonts/Rubik-MediumItalic.ttf

    - family: Rubik-Regular
      fonts:
        - asset: fonts/Rubik-Regular.ttf

  assets:
    - assets/
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
